# Copyright 2021 Stan Grishin (stangri@melmac.ca)
# This is free software, licensed under the GNU General Public License v3.

include $(TOPDIR)/rules.mk

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=bulanovk
PKG_VERSION:=0.0.1-1
LUCI_TITLE:=Support for Intel NCM
LUCI_DESCRIPTION:=Provides Web UI for Intel NCM protocol/interface.
#LUCI_DEPENDS:=+nebula +nebula-proto
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
